**CAR PRICE PREDICTION BY VISHAL**

**Goal**: Predict the Price of a car (numeric target) using features like Make, Model, Year, Kilometer, Engine, Max Power, Fuel Type, Transmission, etc.

**Type of problem**: Supervised regression

In [60]:
# Import Required Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [61]:
# Load Dataset
df=pd.read_csv('car_details.csv')

In [62]:
df

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [63]:
# Column names
df.columns

Index(['Make', 'Model', 'Price', 'Year', 'Kilometer', 'Fuel Type',
       'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Engine',
       'Max Power', 'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height',
       'Seating Capacity', 'Fuel Tank Capacity'],
      dtype='object')

In [64]:
# Total Columns
a=df.columns.to_list()
a
len(a)

20

In [65]:
# Basic Information of Data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   object
 1   Model               2059 non-null   object
 2   Price               2059 non-null   int64
 3   Year                2059 non-null   int64
 4   Kilometer           2059 non-null   int64
 5   Fuel Type           2059 non-null   object
 6   Transmission        2059 non-null   object
 7   Location            2059 non-null   object
 8   Color               2059 non-null   object
 9   Owner               2059 non-null   object
 10  Seller Type         2059 non-null   object
 11  Engine              1979 non-null   object
 12  Max Power           1979 non-null   object
 13  Max Torque          1979 non-null   object
 14  Drivetrain          1923 non-null   object
 15  Length              1995 non-null   float64
 16  Width               1995 non-null   float64
 17  Height              1995 non-null   float64
 18  Seating Capacity    1995 non-null   float64
 19  Fuel Tank Capacity  1946 non-null   float64
dtypes: float64(5), int64(3), object(12)
memory usage: 321.8+ KB

In [66]:
# Count Null Values
df.isnull().sum()

Make                    0
Model                   0
Price                   0
Year                    0
Kilometer               0
Fuel Type               0
Transmission            0
Location                0
Color                   0
Owner                   0
Seller Type             0
Engine                 80
Max Power              80
Max Torque             80
Drivetrain            136
Length                 64
Width                  64
Height                 64
Seating Capacity       64
Fuel Tank Capacity    113
dtype: int64

In [67]:
#Drop rows where Price is missing (target variable must be complete)
df = df.dropna(subset=['Price'])

In [68]:
# Make y as a Target Variable
y=df['Price']

In [69]:
print(y.isnull().sum())

0

In [70]:
y

0        505000
1        450000
2        220000
3        799000
4       1950000
         ...
2054     850000
2055     275000
2056     240000
2057    4290000
2058     670000
Name: Price, Length: 2059, dtype: int64

In [71]:
# years
df['Year'].unique()

array([2017, 2014, 2011, 2019, 2018, 2015, 2016, 2020, 2013, 2009, 2010,
       2021, 2012, 2006, 2022, 2007, 2008, 2004, 2002, 1988, 2000, 1996])

In [72]:
# Create derived feature: Car Age
df['Car_Age'] = 2025 - df['Year']

In [73]:
df['Car_Age'].unique()

array([ 8, 11, 14,  6,  7, 10,  9,  5, 12, 16, 15,  4, 13, 19,  3, 18, 17,
       21, 23, 37, 25, 29])

In [74]:
df

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,...,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity,Car_Age
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,...,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0,8
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,...,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0,11
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,...,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0,14
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,...,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0,6
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,...,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,...,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0,9
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,...,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0,11
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,...,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0,12
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,...,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0,7
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,...,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN,8

In [75]:
df.columns

Index(['Make', 'Model', 'Price', 'Year', 'Kilometer', 'Fuel Type',
       'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Engine',
       'Max Power', 'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height',
       'Seating Capacity', 'Fuel Tank Capacity', 'Car_Age'],
      dtype='object')

In [76]:
# Drop year column as it is not required
df.drop(["Year"], axis=1, inplace=True)

In [77]:
df.columns

Index(['Make', 'Model', 'Price', 'Kilometer', 'Fuel Type', 'Transmission',
       'Location', 'Color', 'Owner', 'Seller Type', 'Engine', 'Max Power',
       'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height',
       'Seating Capacity', 'Fuel Tank Capacity', 'Car_Age'],
      dtype='object')

In [78]:
# Rename a Column and remove the Units
df['Engine (cc)'] = df['Engine'].astype(str).str.replace('cc', '', regex=False)

In [79]:
df.columns

Index(['Make', 'Model', 'Price', 'Kilometer', 'Fuel Type', 'Transmission',
       'Location', 'Color', 'Owner', 'Seller Type', 'Engine', 'Max Power',
       'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height',
       'Seating Capacity', 'Fuel Tank Capacity', 'Car_Age', 'Engine (cc)'],
      dtype='object')

In [80]:
# Drop Engine Column as it is not required
df.drop(['Engine'],axis=1,inplace=True)

In [81]:
# Split Max Power into two columns using @
df[['Max Power (BHP)', 'Max Power (RPM)']] = df['Max Power'].str.split('@', expand=True)

In [82]:
df

,Make,Model,Price,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,...,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity,Car_Age,Engine (cc),Max Power (BHP),Max Power (RPM)
0,Honda,Amaze 1.2 VX i-VTEC,505000,87150,Petrol,Manual,Pune,Grey,First,Corporate,...,FWD,3990.0,1680.0,1505.0,5.0,35.0,8,1198,87 bhp,6000 rpm
1,Maruti Suzuki,Swift DZire VDI,450000,75000,Diesel,Manual,Ludhiana,White,Second,Individual,...,FWD,3995.0,1695.0,1555.0,5.0,42.0,11,1248,74 bhp,4000 rpm
2,Hyundai,i10 Magna 1.2 Kappa2,220000,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,...,FWD,3585.0,1595.0,1550.0,5.0,35.0,14,1197,79 bhp,6000 rpm
3,Toyota,Glanza G,799000,37500,Petrol,Manual,Mangalore,Red,First,Individual,...,FWD,3995.0,1745.0,1510.0,5.0,37.0,6,1197,82 bhp,6000 rpm
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,69000,Diesel,Manual,Mumbai,Grey,First,Individual,...,RWD,4735.0,1830.0,1795.0,7.0,55.0,7,2393,148 bhp,3400 rpm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,90300,Diesel,Manual,Surat,White,First,Individual,...,FWD,4585.0,1890.0,1785.0,7.0,70.0,9,2179,138 bhp,3750 rpm
2055,Hyundai,Eon D-Lite +,275000,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,...,FWD,3495.0,1550.0,1500.0,5.0,32.0,11,814,55 bhp,5500 rpm
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,73000,Petrol,Manual,Thane,Silver,First,Individual,...,FWD,3795.0,1680.0,1427.0,5.0,45.0,12,1196,70 bhp,6250 rpm
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,60474,Diesel,Automatic,Coimbatore,White,First,Individual,...,RWD,4936.0,1868.0,1479.0,5.0,65.0,7,1995,188 bhp,4000 rpm
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,72000,Diesel,Manual,Guwahati,White,First,Individual,...,RWD,3995.0,1745.0,1880.0,7.0,NaN,8,1493,70 bhp,3600 rpm

In [83]:
# Remove the units from the columns
df['Max Power (BHP)'] = df['Max Power (BHP)'].astype(str).str.replace('bhp', '', regex=False)
df['Max Power (RPM)'] = df['Max Power (RPM)'].astype(str).str.replace('rpm', '', regex=False)

In [84]:
df

,Make,Model,Price,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,...,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity,Car_Age,Engine (cc),Max Power (BHP),Max Power (RPM)
0,Honda,Amaze 1.2 VX i-VTEC,505000,87150,Petrol,Manual,Pune,Grey,First,Corporate,...,FWD,3990.0,1680.0,1505.0,5.0,35.0,8,1198,87,6000
1,Maruti Suzuki,Swift DZire VDI,450000,75000,Diesel,Manual,Ludhiana,White,Second,Individual,...,FWD,3995.0,1695.0,1555.0,5.0,42.0,11,1248,74,4000
2,Hyundai,i10 Magna 1.2 Kappa2,220000,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,...,FWD,3585.0,1595.0,1550.0,5.0,35.0,14,1197,79,6000
3,Toyota,Glanza G,799000,37500,Petrol,Manual,Mangalore,Red,First,Individual,...,FWD,3995.0,1745.0,1510.0,5.0,37.0,6,1197,82,6000
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,69000,Diesel,Manual,Mumbai,Grey,First,Individual,...,RWD,4735.0,1830.0,1795.0,7.0,55.0,7,2393,148,3400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,90300,Diesel,Manual,Surat,White,First,Individual,...,FWD,4585.0,1890.0,1785.0,7.0,70.0,9,2179,138,3750
2055,Hyundai,Eon D-Lite +,275000,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,...,FWD,3495.0,1550.0,1500.0,5.0,32.0,11,814,55,5500
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,73000,Petrol,Manual,Thane,Silver,First,Individual,...,FWD,3795.0,1680.0,1427.0,5.0,45.0,12,1196,70,6250
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,60474,Diesel,Automatic,Coimbatore,White,First,Individual,...,RWD,4936.0,1868.0,1479.0,5.0,65.0,7,1995,188,4000
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,72000,Diesel,Manual,Guwahati,White,First,Individual,...,RWD,3995.0,1745.0,1880.0,7.0,NaN,8,1493,70,3600

In [85]:
# Drop Max Power as it is not required
df.drop(['Max Power'],axis=1,inplace=True)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   object
 1   Model               2059 non-null   object
 2   Price               2059 non-null   int64
 3   Kilometer           2059 non-null   int64
 4   Fuel Type           2059 non-null   object
 5   Transmission        2059 non-null   object
 6   Location            2059 non-null   object
 7   Color               2059 non-null   object
 8   Owner               2059 non-null   object
 9   Seller Type         2059 non-null   object
 10  Max Torque          1979 non-null   object
 11  Drivetrain          1923 non-null   object
 12  Length              1995 non-null   float64
 13  Width               1995 non-null   float64
 14  Height              1995 non-null   float64
 15  Seating Capacity    1995 non-null   float64
 16  Fuel Tank Capacity  1946 non-null   float64
 17  Car_Age             2059 non-null   int64
 18  Engine (cc)         2059 non-null   object
 19  Max Power (BHP)     2059 non-null   object
 20  Max Power (RPM)     2059 non-null   object
dtypes: float64(5), int64(3), object(13)
memory usage: 337.9+ KB

In [87]:
#Drop unnecessary columns
df.drop(['Price', 'Max Torque', 'Color'], axis=1, inplace=True, errors='ignore')

In [88]:
df

,Make,Model,Kilometer,Fuel Type,Transmission,Location,Owner,Seller Type,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity,Car_Age,Engine (cc),Max Power (BHP),Max Power (RPM)
0,Honda,Amaze 1.2 VX i-VTEC,87150,Petrol,Manual,Pune,First,Corporate,FWD,3990.0,1680.0,1505.0,5.0,35.0,8,1198,87,6000
1,Maruti Suzuki,Swift DZire VDI,75000,Diesel,Manual,Ludhiana,Second,Individual,FWD,3995.0,1695.0,1555.0,5.0,42.0,11,1248,74,4000
2,Hyundai,i10 Magna 1.2 Kappa2,67000,Petrol,Manual,Lucknow,First,Individual,FWD,3585.0,1595.0,1550.0,5.0,35.0,14,1197,79,6000
3,Toyota,Glanza G,37500,Petrol,Manual,Mangalore,First,Individual,FWD,3995.0,1745.0,1510.0,5.0,37.0,6,1197,82,6000
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],69000,Diesel,Manual,Mumbai,First,Individual,RWD,4735.0,1830.0,1795.0,7.0,55.0,7,2393,148,3400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],90300,Diesel,Manual,Surat,First,Individual,FWD,4585.0,1890.0,1785.0,7.0,70.0,9,2179,138,3750
2055,Hyundai,Eon D-Lite +,83000,Petrol,Manual,Ahmedabad,Second,Individual,FWD,3495.0,1550.0,1500.0,5.0,32.0,11,814,55,5500
2056,Ford,Figo Duratec Petrol ZXI 1.2,73000,Petrol,Manual,Thane,First,Individual,FWD,3795.0,1680.0,1427.0,5.0,45.0,12,1196,70,6250
2057,BMW,5-Series 520d Luxury Line [2017-2019],60474,Diesel,Automatic,Coimbatore,First,Individual,RWD,4936.0,1868.0,1479.0,5.0,65.0,7,1995,188,4000
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],72000,Diesel,Manual,Guwahati,First,Individual,RWD,3995.0,1745.0,1880.0,7.0,NaN,8,1493,70,3600

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   object
 1   Model               2059 non-null   object
 2   Kilometer           2059 non-null   int64
 3   Fuel Type           2059 non-null   object
 4   Transmission        2059 non-null   object
 5   Location            2059 non-null   object
 6   Owner               2059 non-null   object
 7   Seller Type         2059 non-null   object
 8   Drivetrain          1923 non-null   object
 9   Length              1995 non-null   float64
 10  Width               1995 non-null   float64
 11  Height              1995 non-null   float64
 12  Seating Capacity    1995 non-null   float64
 13  Fuel Tank Capacity  1946 non-null   float64
 14  Car_Age             2059 non-null   int64
 15  Engine (cc)         2059 non-null   object
 16  Max Power (BHP)     2059 non-null   object
 17  Max Power (RPM)     2059 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 289.7+ KB

In [90]:
# Object to Numric Convertion
df['Engine (cc)'] = pd.to_numeric(df['Engine (cc)'], errors='coerce')
df['Max Power (BHP)'] = pd.to_numeric(df['Max Power (BHP)'], errors='coerce')
df['Max Power (RPM)'] = pd.to_numeric(df['Max Power (RPM)'], errors='coerce')

In [91]:
# Filling Null values with mean
cols = ['Engine (cc)', 'Max Power (BHP)', 'Max Power (RPM)']
df[cols] = df[cols].fillna(df[cols].mean())

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   object
 1   Model               2059 non-null   object
 2   Kilometer           2059 non-null   int64
 3   Fuel Type           2059 non-null   object
 4   Transmission        2059 non-null   object
 5   Location            2059 non-null   object
 6   Owner               2059 non-null   object
 7   Seller Type         2059 non-null   object
 8   Drivetrain          1923 non-null   object
 9   Length              1995 non-null   float64
 10  Width               1995 non-null   float64
 11  Height              1995 non-null   float64
 12  Seating Capacity    1995 non-null   float64
 13  Fuel Tank Capacity  1946 non-null   float64
 14  Car_Age             2059 non-null   int64
 15  Engine (cc)         2059 non-null   float64
 16  Max Power (BHP)     2059 non-null   float64
 17  Max Power (RPM)     2059 non-null   float64
dtypes: float64(8), int64(2), object(8)
memory usage: 289.7+ KB

In [93]:
# Handle missing values for numerical columns using Mean
for col in ['Kilometer', 'Length', 'Width', 'Height', 'Seating Capacity', 'Fuel Tank Capacity','Car_Age']:
  if col in df.columns:
    df[col] = df[col].fillna(df[col].mean())

In [94]:
df.isnull().sum()

Make                    0
Model                   0
Kilometer               0
Fuel Type               0
Transmission            0
Location                0
Owner                   0
Seller Type             0
Drivetrain            136
Length                  0
Width                   0
Height                  0
Seating Capacity        0
Fuel Tank Capacity      0
Car_Age                 0
Engine (cc)             0
Max Power (BHP)         0
Max Power (RPM)         0
dtype: int64

In [95]:
# Handling missing values for categorical columns using Mode
df['Drivetrain']=df['Drivetrain'].fillna(df['Drivetrain'].mode()[0])

In [96]:
df.isnull().sum()

Make                  0
Model                 0
Kilometer             0
Fuel Type             0
Transmission          0
Location              0
Owner                 0
Seller Type           0
Drivetrain            0
Length                0
Width                 0
Height                0
Seating Capacity      0
Fuel Tank Capacity    0
Car_Age               0
Engine (cc)           0
Max Power (BHP)       0
Max Power (RPM)       0
dtype: int64

In [97]:
# Float to int conversion
for col in df.select_dtypes(include=['float']).columns:
    df[col] = df[col].astype(int)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   object
 1   Model               2059 non-null   object
 2   Kilometer           2059 non-null   int64
 3   Fuel Type           2059 non-null   object
 4   Transmission        2059 non-null   object
 5   Location            2059 non-null   object
 6   Owner               2059 non-null   object
 7   Seller Type         2059 non-null   object
 8   Drivetrain          2059 non-null   object
 9   Length              2059 non-null   int64
 10  Width               2059 non-null   int64
 11  Height              2059 non-null   int64
 12  Seating Capacity    2059 non-null   int64
 13  Fuel Tank Capacity  2059 non-null   int64
 14  Car_Age             2059 non-null   int64
 15  Engine (cc)         2059 non-null   int64
 16  Max Power (BHP)     2059 non-null   int64
 17  Max Power (RPM)     2059 non-null   int64
dtypes: int64(10), object(8)
memory usage: 289.7+ KB

In [99]:
# ✅ Label Encode categorical columns
from sklearn.preprocessing import LabelEncoder

for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()  # create a new encoder for each column
    df[col] = le.fit_transform(df[col].astype(str))

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   int64
 1   Model               2059 non-null   int64
 2   Kilometer           2059 non-null   int64
 3   Fuel Type           2059 non-null   int64
 4   Transmission        2059 non-null   int64
 5   Location            2059 non-null   int64
 6   Owner               2059 non-null   int64
 7   Seller Type         2059 non-null   int64
 8   Drivetrain          2059 non-null   int64
 9   Length              2059 non-null   int64
 10  Width               2059 non-null   int64
 11  Height              2059 non-null   int64
 12  Seating Capacity    2059 non-null   int64
 13  Fuel Tank Capacity  2059 non-null   int64
 14  Car_Age             2059 non-null   int64
 15  Engine (cc)         2059 non-null   int64
 16  Max Power (BHP)     2059 non-null   int64
 17  Max Power (RPM)     2059 non-null   int64
dtypes: int64(18)
memory usage: 289.7 KB

In [101]:
x=df

In [102]:
x

,Make,Model,Kilometer,Fuel Type,Transmission,Location,Owner,Seller Type,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity,Car_Age,Engine (cc),Max Power (BHP),Max Power (RPM)
0,7,106,87150,6,1,56,1,1,1,3990,1680,1505,5,35,8,1198,87,6000
1,19,802,75000,2,1,40,3,2,1,3995,1695,1555,5,42,11,1248,74,4000
2,8,1030,67000,6,1,39,1,2,1,3585,1595,1550,5,35,14,1197,79,6000
3,30,492,37500,6,1,41,1,2,1,3995,1745,1510,5,37,6,1197,82,6000
4,30,548,69000,2,1,45,1,2,2,4735,1830,1795,7,55,7,2393,148,3400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,18,999,90300,2,1,67,1,2,1,4585,1890,1785,7,70,9,2179,138,3750
2055,8,414,83000,6,1,1,3,2,1,3495,1550,1500,5,32,11,814,55,5500
2056,6,455,73000,6,1,68,1,2,1,3795,1680,1427,5,45,12,1196,70,6250
2057,1,13,60474,2,0,12,1,2,2,4936,1868,1479,5,65,7,1995,188,4000
2058,18,138,72000,2,1,25,1,2,2,3995,1745,1880,7,52,8,1493,70,3600

In [103]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   int64
 1   Model               2059 non-null   int64
 2   Kilometer           2059 non-null   int64
 3   Fuel Type           2059 non-null   int64
 4   Transmission        2059 non-null   int64
 5   Location            2059 non-null   int64
 6   Owner               2059 non-null   int64
 7   Seller Type         2059 non-null   int64
 8   Drivetrain          2059 non-null   int64
 9   Length              2059 non-null   int64
 10  Width               2059 non-null   int64
 11  Height              2059 non-null   int64
 12  Seating Capacity    2059 non-null   int64
 13  Fuel Tank Capacity  2059 non-null   int64
 14  Car_Age             2059 non-null   int64
 15  Engine (cc)         2059 non-null   int64
 16  Max Power (BHP)     2059 non-null   int64
 17  Max Power (RPM)     2059 non-null   int64
dtypes: int64(18)
memory usage: 289.7 KB

In [104]:
# Finding best random state with R2 score
best_r2 = -1
best_state = 0

for i in range(0, 100):
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=i)

    lr = LinearRegression()
    lr.fit(X_train, y_train)

    y_pred = lr.predict(X_test)
    r2 = r2_score(y_test, y_pred)

    print(f'Random state {i} R2 score: {r2:.4f}')

    if r2 > best_r2:
        best_r2 = r2
        best_state = i

print(f'\nBest random state: {best_state} with R2 score: {best_r2:.4f}')

Random state 0 R2 score: 0.6992
Random state 1 R2 score: 0.6500
Random state 2 R2 score: 0.7101
Random state 3 R2 score: 0.7529
Random state 4 R2 score: 0.7492
Random state 5 R2 score: 0.6460
Random state 6 R2 score: 0.5964
Random state 7 R2 score: 0.7311
Random state 8 R2 score: 0.6239
Random state 9 R2 score: 0.6296
Random state 10 R2 score: 0.6464
Random state 11 R2 score: 0.6196
Random state 12 R2 score: 0.7668
Random state 13 R2 score: 0.6200
Random state 14 R2 score: 0.6625
Random state 15 R2 score: 0.6014
Random state 16 R2 score: 0.7448
Random state 17 R2 score: 0.6411
Random state 18 R2 score: 0.5117
Random state 19 R2 score: 0.6195
Random state 20 R2 score: 0.5551
Random state 21 R2 score: 0.7344
Random state 22 R2 score: 0.6591
Random state 23 R2 score: 0.6980
Random state 24 R2 score: 0.7919
Random state 25 R2 score: 0.7033
Random state 26 R2 score: 0.4690
Random state 27 R2 score: 0.5880
Random state 28 R2 score: 0.6215
Random state 29 R2 score: 0.7638
Random state 30 R2 score: 0.7167
Random state 31 R2 score: 0.6950
Random state 32 R2 score: 0.6953
Random state 33 R2 score: 0.5964
Random state 34 R2 score: 0.7690
Random state 35 R2 score: 0.6420
Random state 36 R2 score: 0.6029
Random state 37 R2 score: 0.5136
Random state 38 R2 score: 0.7171
Random state 39 R2 score: 0.7066
Random state 40 R2 score: 0.6954
Random state 41 R2 score: 0.6519
Random state 42 R2 score: 0.7240
Random state 43 R2 score: 0.5091
Random state 44 R2 score: 0.7276
Random state 45 R2 score: 0.5184
Random state 46 R2 score: 0.6171
Random state 47 R2 score: 0.7099
Random state 48 R2 score: 0.4568
Random state 49 R2 score: 0.7367
Random state 50 R2 score: 0.6273
Random state 51 R2 score: 0.4653
Random state 52 R2 score: 0.7394
Random state 53 R2 score: 0.7068
Random state 54 R2 score: 0.6161
Random state 55 R2 score: 0.5449
Random state 56 R2 score: 0.6641
Random state 57 R2 score: 0.6801
Random state 58 R2 score: 0.6642
Random state 59 R2 score: 0.5619
Random state 60 R2 score: 0.7485
Random state 61 R2 score: 0.3747
Random state 62 R2 score: 0.5702
Random state 63 R2 score: 0.6528
Random state 64 R2 score: 0.6462
Random state 65 R2 score: 0.7799
Random state 66 R2 score: 0.6121
Random state 67 R2 score: 0.5895
Random state 68 R2 score: 0.6285
Random state 69 R2 score: 0.5989
Random state 70 R2 score: 0.6785
Random state 71 R2 score: 0.7875
Random state 72 R2 score: 0.7968
Random state 73 R2 score: 0.6366
Random state 74 R2 score: 0.6963
Random state 75 R2 score: 0.7249
Random state 76 R2 score: 0.6615
Random state 77 R2 score: 0.6495
Random state 78 R2 score: 0.6704
Random state 79 R2 score: 0.6126
Random state 80 R2 score: 0.6509
Random state 81 R2 score: 0.7628
Random state 82 R2 score: 0.6974
Random state 83 R2 score: 0.5919
Random state 84 R2 score: 0.6156
Random state 85 R2 score: 0.6335
Random state 86 R2 score: 0.6974
Random state 87 R2 score: 0.7522
Random state 88 R2 score: 0.6806
Random state 89 R2 score: 0.7050
Random state 90 R2 score: 0.6619
Random state 91 R2 score: 0.6990
Random state 92 R2 score: 0.6342
Random state 93 R2 score: 0.5837
Random state 94 R2 score: 0.6399
Random state 95 R2 score: 0.7067
Random state 96 R2 score: 0.6783
Random state 97 R2 score: 0.6417
Random state 98 R2 score: 0.6702
Random state 99 R2 score: 0.6764

Best random state: 72 with R2 score: 0.7968

In [105]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=72)

In [106]:
# Traning Model
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [107]:
# Model Prediction
y_pred = lr.predict(X_test)

In [108]:
# Model Evaluation
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)

print(f" R2: {r2:.4f}\n mse:{mse:.4f}\n RMSE: {rmse:.4f}\n MAE: {mae:.4f}")

 R2: 0.7968
 mse:1323467138595.2527
 RMSE: 1150420.4182
 MAE: 761743.9241

In [109]:
# Creating Pickle File
import joblib
joblib.dump(lr,"Final_Linear_Model.pkl")
print("pkl file is created!")

pkl file is created!

In [110]:
# Cleaned Dataset --> CSV
x.to_csv('cleaned_car_price_data.csv', index=False)

## **OUR MODEL IS READY ✌**